/**
 * Generates SEO_CONTENT_ROADMAP.md from the live content modules.
 *
 * Generated rather than hand-written so the roadmap cannot drift from what the
 * application actually publishes: change a meta description in code and the
 * roadmap changes with it on the next run.
 *
 * Run: node --import ./scripts/seo/alias-hooks.mjs scripts/seo/content-roadmap.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const load = (rel) => import(pathToFileURL(path.join(ROOT, rel)).href);

const { productSeoContent } = await load("lib/seo/content/products.ts");
const { collectionSeoContent } = await load("lib/seo/content/collections.ts");
const { industryPages } = await load("lib/seo/content/industries.ts");
const { useCasePages } = await load("lib/seo/content/use-cases.ts");
const { occasionPages } = await load("lib/seo/content/occasions.ts");
const { giftSetPages } = await load("lib/seo/content/gift-sets.ts");
const { guidePages } = await load("lib/seo/content/guides.ts");
const { productClusterLinks } = await load("lib/seo/content/clusters.ts");

const out = [];
const w = (s = "") => out.push(s);

w("# SEO Content Roadmap");
w();
w("Generated by `scripts/seo/content-roadmap.mjs` from the live content modules in");
w("`lib/seo/content/`. Do not edit by hand -- edit the source module and re-run.");
w();
w("Every indexable, editorially-owned page on the storefront is listed below with the");
w("keyword it owns, the copy it ships, the schema it emits and where it links.");
w();
w("| Tier | Pages | Owns |");
w("| --- | --- | --- |");
w("| Homepage | 1 | Broad brand-level head terms |");
w(`| Category pages | ${collectionSeoContent.length} | Cluster head terms |`);
w(`| Product pages | ${productSeoContent.length} | One long-tail term each |`);
w(`| Industry landing | ${industryPages.length} | Sector-specific commercial terms |`);
w(`| Use-case landing | ${useCasePages.length} | Occasion / programme terms |`);
w(`| Occasion landing | ${occasionPages.length} | Seasonal terms (evergreen URLs) |`);
w(`| Multi-piece sets | ${giftSetPages.length} | Piece-count terms |`);
w(`| Guides | ${guidePages.length} | Informational / research terms |`);
w();

/* ---------------- homepage ---------------- */
w("---");
w();
w("## Homepage");
w();
w("- **URL:** `/`");
w("- **Page type:** homepage");
w("- **Primary keywords:** corporate gifts, corporate gifting company, personalized corporate gifts, custom gift sets with logo, bulk corporate gifts online");
w("- **Search intent:** commercial investigation / navigational");
w("- **Funnel stage:** top-to-middle");
w("- **Target audience:** HR, admin, procurement and marketing buyers evaluating a supplier");
w("- **Content purpose:** establish what the company supplies and route visitors down to the tier that matches their situation");
w("- **H1:** rendered by `components/home/Hero.tsx` (unchanged -- conversion-owned)");
w("- **SEO title:** Corporate Gifts & Personalized Corporate Gifting | Gifta Guru");
w("- **Meta description:** Corporate gifts and custom gift sets with logo branding. Employee welcome kits, client gifting, luxury and eco sets, with bulk pricing across India.");
w("- **Sections:** hero, benefits, categories, why-choose-us, solutions, customization, how it works, featured products, **SEO intro + four-column link block (new)**, bulk CTA, testimonials, FAQ");
w("- **Internal links out:** 16 (4 collections, 4 use-cases/occasions, 4 industries, 4 guides/tools)");
w("- **Schema:** Organization + WebSite (root layout), FAQPage");
w("- **CTA:** Request a bulk quote");
w("- **Priority:** 1");
w();

/* ---------------- categories ---------------- */
w("---");
w();
w("## Category pages");
w();
for (const c of collectionSeoContent) {
  w(`### /categories/${c.slug}`);
  w();
  w(`- **Primary keyword:** ${c.primaryKeyword}`);
  w(`- **Secondary keywords:** ${c.secondaryKeywords.join(", ")}`);
  w("- **Search intent:** commercial investigation (browse)");
  w("- **Funnel stage:** middle");
  w("- **Page type:** category / collection listing");
  w("- **Target audience:** buyers who know the gift category but not the specific set");
  w("- **Content purpose:** own the cluster head term and route to the right product");
  w(`- **H1:** ${c.h1}`);
  w(`- **SEO title:** ${c.seoTitle} | Gifta Guru`);
  w(`- **Meta description:** ${c.metaDescription}`);
  w("- **Sections:** intro copy, product grid, how to choose from this collection, FAQs, continue exploring");
  w(`- **FAQs:** ${c.faqs.length}`);
  w(`- **Internal links:** ${c.relatedLinks.map((l) => `[${l.label}](${l.href})`).join(", ")}`);
  w("- **Schema:** BreadcrumbList, ItemList, FAQPage");
  w("- **CTA:** Request a Custom Quote");
  w("- **Priority:** 1");
  w();
}

/* ---------------- products ---------------- */
w("---");
w();
w("## Product pages");
w();
w("Each owns one distinct long-tail primary keyword and links UP to its cluster.");
w("None targets a cluster head term.");
w();
for (const p of productSeoContent) {
  w(`### /products/${p.slug}`);
  w();
  w(`- **Cluster:** ${p.cluster}`);
  w(`- **Primary keyword:** ${p.primaryKeyword}`);
  w(`- **Secondary keywords:** ${p.secondaryKeywords.join(", ")}`);
  w("- **Search intent:** transactional");
  w("- **Funnel stage:** bottom");
  w("- **Target audience:** buyer comparing specific sets for a known occasion");
  w(`- **H1:** ${p.h1}`);
  w(`- **SEO title:** ${p.seoTitle} | Gifta Guru`);
  w(`- **Meta description:** ${p.metaDescription}`);
  w(`- **Sections:** gallery + purchase panel, volume pricing, delivery/fulfilment, product details accordion, about this gift set (${p.detailedDescription.length} paragraphs), key features (${p.keyFeatures.length}), who it's for (${p.useCases.length}), FAQs (${p.faqs.length}), explore related gifting, related products`);
  w(`- **Internal links:** ${(productClusterLinks[p.cluster] ?? []).map((l) => `[${l.label}](${l.href})`).join(", ")}`);
  w("- **Schema:** BreadcrumbList, Product + Offer, FAQPage");
  w("- **CTA:** Add to cart / Request a quote for larger quantities");
  w("- **Priority:** 1");
  w();
}

/* ---------------- landing families ---------------- */
const families = [
  ["Industry landing pages", "/industries", industryPages, "commercial investigation (sector-specific)", "middle"],
  ["Use-case landing pages", "/gifting", useCasePages, "commercial investigation (occasion-led)", "middle"],
  ["Occasion / seasonal pages", "/occasions", occasionPages, "seasonal commercial", "middle"],
  ["Multi-piece gift set pages", "/gift-sets", giftSetPages, "transactional (specification-led)", "middle-to-bottom"],
  ["Guides", "/guides", guidePages, "informational", "top"],
];

for (const [title, base, pages, intent, stage] of families) {
  w("---");
  w();
  w(`## ${title}`);
  w();
  for (const p of pages) {
    const words = [
      ...p.intro,
      ...p.sections.flatMap((s) => [...(s.body ?? []), ...(s.bullets ?? [])]),
      ...p.faqs.flatMap((f) => [f.question, f.answer]),
    ].join(" ").split(/\s+/).length;

    w(`### ${base}/${p.slug}`);
    w();
    w(`- **Primary keyword:** ${p.primaryKeyword}`);
    w(`- **Secondary keywords:** ${p.secondaryKeywords.join(", ")}`);
    w(`- **Search intent:** ${intent}`);
    w(`- **Funnel stage:** ${stage}`);
    w(`- **H1:** ${p.h1}`);
    w(`- **SEO title:** ${p.seoTitle} | Gifta Guru`);
    w(`- **Meta description:** ${p.metaDescription}`);
    w(`- **Sections (${p.sections.length}):** ${p.sections.map((s) => s.heading).join("; ")}`);
    w(`- **Word count:** ~${words}`);
    w(`- **FAQs:** ${p.faqs.length}`);
    w(`- **Recommended products:** ${p.recommendedProductSlugs.join(", ")}`);
    w(`- **Internal links:** ${p.relatedLinks.map((l) => `[${l.label}](${l.href})`).join(", ")}`);
    w("- **Schema:** BreadcrumbList, FAQPage");
    w("- **CTA:** Request a Custom Quote");
    w(`- **Priority:** ${base === "/guides" ? 3 : 2}`);
    w();
  }
}

/* ---------------- seasonal calendar ---------------- */
w("---");
w();
w("## 12-month seasonal content calendar");
w();
w("Seasonal pages are evergreen URLs updated in place, not rebuilt annually. The");
w("months below are when each page should be REFRESHED and promoted, which is");
w("deliberately ahead of when the demand peaks -- seasonal search demand climbs");
w("well before the occasion, and a page published during the peak has missed it.");
w();
w("| Month | Focus | Page | Supporting guide | Products to feature |");
w("| --- | --- | --- | --- | --- |");
w("| January | New-year planners, Q1 kickoff | /occasions/new-year-corporate-gifts | /guides/corporate-gifting-guide | Grey planner set, luxury planner box |");
w("| February | Appreciation cycle, annual reviews | /gifting/employee-appreciation | /guides/corporate-gifting-budget-guide | Journal & pen, grey planner |");
w("| March | Financial year end, budget planning | /gifting/bulk-corporate-gifting | /guides/corporate-gifting-budget-guide | Minimal notebook, compact welcome kit |");
w("| April | New financial year onboarding, Earth Day | /gifting/employee-onboarding | /guides/eco-friendly-corporate-gifting | Compact welcome kit, sage green set |");
w("| May | Campus/graduate intake prep | /guides/employee-welcome-kit-guide | /gift-sets/3-piece-corporate-gift-sets | Compact welcome kit, blue notebook |");
w("| June | Mid-year conferences, environment campaigns | /gifting/events-conferences | /guides/conference-giveaway-guide | Minimal notebook, green eco notebook |");
w("| July | Dealer and channel planning | /gifting/dealer-channel-partner | /guides/logo-branding-on-corporate-gifts | Complete stationery, black & gold |");
w("| **August** | **Diwali planning starts** | /occasions/diwali-corporate-gifts | /guides/diwali-corporate-gifting-guide | Burgundy set, black & gold, white premium |");
w("| **September** | **Festive ordering window** | /occasions/festive-corporate-gifting | /guides/client-gifting-guide | Burgundy, luxury planner, complete stationery |");
w("| October | Festive fulfilment, late orders | /occasions/diwali-corporate-gifts | /guides/diwali-corporate-gifting-guide | In-stock premium sets |");
w("| **November** | **New-year gifting ordering** | /occasions/new-year-corporate-gifts | /gifting/executive-leadership | Luxury planner box, grey planner |");
w("| December | Year-end thanks, wedding season | /occasions/wedding-season-corporate-gifting | /gifting/client-appreciation | Burgundy, white premium, complete stationery |");
w();
w("Bold rows are the two windows that matter most: Diwali planning must begin in");
w("August, and new-year planner gifting must be ordered in November to arrive");
w("before the planner stops being useful.");
w();

fs.writeFileSync(path.join(ROOT, "SEO_CONTENT_ROADMAP.md"), out.join("\n"));
console.log(`Wrote SEO_CONTENT_ROADMAP.md (${out.length} lines)`);
